tracker:
    resource: "@TrackerBundle/Resources/config/routing.yml"
    prefix:   /tracker

logger:
    resource: "@LoggerBundle/Controller/"
    type:     annotation
    prefix:   /

movie:
    resource: "@MovieBundle/Controller/"
    type:     annotation
    prefix:   /
