# Tracker
tracker_dashboard:
    path:      /tracker/dashboard
    defaults:  { _controller: TrackerBundle:Tracker:dashboard }
tracker_record:
    path:      /tracker/record/{recordId}
    defaults:  { _controller: TrackerBundle:Tracker:recordDetail }
track:
    path:      /tracker/track
    defaults:  { _controller: TrackerBundle:Tracker:track }

