# Tracker
tracker_dashboard:
    path:      /tracker/dashboard
    defaults:  { _controller: TrackerBundle:Tracker:dashbaord }
track:
    path:      /tracker/track
    defaults:  { _controller: TrackerBundle:Tracker:track}

# Testing routes
blog_list:
    path:     /blog
    defaults: { _controller: TrackerBundle:Blog:blog }

post_create:
    path:     /blog/create
    defaults: { _controller: TrackerBundle:Blog:createPost }

post:
    path:     /blog/post/{postSlug}
    defaults: { _controller: TrackerBundle:Blog:post }

