services:
    movie_logger:
        class: LoggerBundle\Services\MovieLogger

    movie_logger_event_listener:
        arguments:
            - "@movie_logger"
        class: LoggerBundle\EventListener\MovieLoggerEventListener
        tags:
            - { name: kernel.event_listener, event: movie.created, method: logNewMovie }
